jobs:
  build:
    machine:
      image: circleci/node:18-browsers
    steps:
      - checkout
      - run: npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 sync ./build s3://digitaltwin-react

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
